services:
  cryptography-atlas:
    build:
      context: .
      dockerfile: Dockerfile
    image: cryptography-atlas
    container_name: cryptography-atlas
    ports:
      - "8183:80"
    restart: unless-stopped

